/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Additional location information.  Possible values:  * AS_INSTRUCTED - As instructed.  * CARPORT - Carport.  * CUSTOMER_PICKUP - Picked up by customer.  * DECK - Deck.  * DOOR_PERSON - Resident.  * FRONT_DESK - Front desk.  * FRONT_DOOR - Front door.  * GARAGE - Garage.  * GUARD - Residential guard.  * MAIL_ROOM - Mail room.  * MAIL_SLOT - Mail slot.  * MAILBOX - Mailbox.  * MC_BOY - Delivered to male child.  * MC_GIRL - Delivered to female child.  * MC_MAN - Delivered to male adult.  *MC_WOMAN - Delivered to female adult.  * NEIGHBOR - Delivered to neighbor.  * OFFICE - Office.  * OUTBUILDING - Outbuilding.  * PATIO - Patio.  * PORCH - Porch.  * REAR_DOOR - Rear door.  * RECEPTIONIST - Receptionist.  * RECEIVER - Resident.  * SECURE_LOCATION - Secure location.  * SIDE_DOOR - Side door.
 */
export type AdditionalLocationInfo = 'AS_INSTRUCTED' | 'CARPORT' | 'CUSTOMER_PICKUP' | 'DECK' | 'DOOR_PERSON' | 'FRONT_DESK' | 'FRONT_DOOR' | 'GARAGE' | 'GUARD' | 'MAIL_ROOM' | 'MAIL_SLOT' | 'MAILBOX' | 'MC_BOY' | 'MC_GIRL' | 'MC_MAN' | 'MC_WOMAN' | 'NEIGHBOR' | 'OFFICE' | 'OUTBUILDING' | 'PATIO' | 'PORCH' | 'REAR_DOOR' | 'RECEPTIONIST' | 'RECEIVER' | 'SECURE_LOCATION' | 'SIDE_DOOR';

export const AdditionalLocationInfo = {
    ASINSTRUCTED: 'AS_INSTRUCTED' as AdditionalLocationInfo,
    CARPORT: 'CARPORT' as AdditionalLocationInfo,
    CUSTOMERPICKUP: 'CUSTOMER_PICKUP' as AdditionalLocationInfo,
    DECK: 'DECK' as AdditionalLocationInfo,
    DOORPERSON: 'DOOR_PERSON' as AdditionalLocationInfo,
    FRONTDESK: 'FRONT_DESK' as AdditionalLocationInfo,
    FRONTDOOR: 'FRONT_DOOR' as AdditionalLocationInfo,
    GARAGE: 'GARAGE' as AdditionalLocationInfo,
    GUARD: 'GUARD' as AdditionalLocationInfo,
    MAILROOM: 'MAIL_ROOM' as AdditionalLocationInfo,
    MAILSLOT: 'MAIL_SLOT' as AdditionalLocationInfo,
    MAILBOX: 'MAILBOX' as AdditionalLocationInfo,
    MCBOY: 'MC_BOY' as AdditionalLocationInfo,
    MCGIRL: 'MC_GIRL' as AdditionalLocationInfo,
    MCMAN: 'MC_MAN' as AdditionalLocationInfo,
    MCWOMAN: 'MC_WOMAN' as AdditionalLocationInfo,
    NEIGHBOR: 'NEIGHBOR' as AdditionalLocationInfo,
    OFFICE: 'OFFICE' as AdditionalLocationInfo,
    OUTBUILDING: 'OUTBUILDING' as AdditionalLocationInfo,
    PATIO: 'PATIO' as AdditionalLocationInfo,
    PORCH: 'PORCH' as AdditionalLocationInfo,
    REARDOOR: 'REAR_DOOR' as AdditionalLocationInfo,
    RECEPTIONIST: 'RECEPTIONIST' as AdditionalLocationInfo,
    RECEIVER: 'RECEIVER' as AdditionalLocationInfo,
    SECURELOCATION: 'SECURE_LOCATION' as AdditionalLocationInfo,
    SIDEDOOR: 'SIDE_DOOR' as AdditionalLocationInfo
};