/**
 * Listings
 * These APIs allow access to pricing data of offers listed by authorizing selling partners as well as certain competitive pricing data related to offers by other selling partners on Amazon.
 *
 * OpenAPI spec version: v1
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Condition } from './condition';
import { LandedPrice } from './landedPrice';
import { ListingPrice } from './listingPrice';
import { Points } from './points';
import { ShippingPrice } from './shippingPrice';

/**
 * The price of an item that is displayed in the Buy Box.
 */
export interface BuyboxPrice { 
    condition: Condition;
    landedPrice: LandedPrice;
    listingPrice: ListingPrice;
    shipping: ShippingPrice;
    points?: Points;
}