/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { Quantity } from './quantity';

/**
 * Item information for creating a fulfillment order.
 */
export interface CreateFulfillmentOrderItem { 
    /**
     * The seller SKU of the item.
     */
    sellerSKU: string;
    /**
     * A fulfillment order item identifier that you create to track your fulfillment order items. You can use this value to disambiguate multiple fulfillment items that have the same SellerSKU. For example, you might assign different SellerFulfillmentOrderItemId values to two items in a fulfillment order that share the same SellerSKU but have different GiftMessage values.
     */
    sellerFulfillmentOrderItemId: string;
    quantity: Quantity;
    /**
     * A message to the gift recipient, if applicable.
     */
    giftMessage?: string;
    /**
     * Item-specific text that displays in recipient-facing materials such as the outbound shipment packing slip.
     */
    displayableComment?: string;
    /**
     * Amazon's fulfillment network SKU of the item.
     */
    fulfillmentNetworkSKU?: string;
    perUnitDeclaredValue?: Currency;
    perUnitPrice?: Currency;
    perUnitTax?: Currency;
}