/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The current delivery status of the package.  Possible values:  * IN_TRANSIT - In transit to the destination address.  * DELIVERED - Delivered to the destination address.  * RETURNING - In the process of being returned to Amazon's fulfillment network.  * RETURNED - Returned to Amazon's fulfillment network.  * UNDELIVERABLE - Undeliverable because package was lost or destroyed.  * DELAYED - Delayed.  * AVAILABLE_FOR_PICKUP - Available for pickup.  * CUSTOMER_ACTION - Requires customer action.
 */
export type CurrentStatus = 'IN_TRANSIT' | 'DELIVERED' | 'RETURNING' | 'RETURNED' | 'UNDELIVERABLE' | 'DELAYED' | 'AVAILABLE_FOR_PICKUP' | 'CUSTOMER_ACTION';

export const CurrentStatus = {
    INTRANSIT: 'IN_TRANSIT' as CurrentStatus,
    DELIVERED: 'DELIVERED' as CurrentStatus,
    RETURNING: 'RETURNING' as CurrentStatus,
    RETURNED: 'RETURNED' as CurrentStatus,
    UNDELIVERABLE: 'UNDELIVERABLE' as CurrentStatus,
    DELAYED: 'DELAYED' as CurrentStatus,
    AVAILABLEFORPICKUP: 'AVAILABLE_FOR_PICKUP' as CurrentStatus,
    CUSTOMERACTION: 'CUSTOMER_ACTION' as CurrentStatus
};