/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';

/**
 * Fee type and cost.
 */
export interface Fee { 
    /**
     * The type of fee.  Possible values:  * FBAPerUnitFulfillmentFee - Estimated fee for each unit in the fulfillment order.  * FBAPerOrderFulfillmentFee - Estimated order-level fee.  * FBATransportationFee - Estimated shipping fee.  * FBAFulfillmentCODFee - Estimated COD (Cash On Delivery) fee. This fee applies only to fulfillment order previews for COD.
     */
    name: Fee.NameEnum;
    amount: Currency;
}
export namespace Fee {
    export type NameEnum = 'FBAPerUnitFulfillmentFee' | 'FBAPerOrderFulfillmentFee' | 'FBATransportationFee' | 'FBAFulfillmentCODFee';
    export const NameEnum = {
        FBAPerUnitFulfillmentFee: 'FBAPerUnitFulfillmentFee' as NameEnum,
        FBAPerOrderFulfillmentFee: 'FBAPerOrderFulfillmentFee' as NameEnum,
        FBATransportationFee: 'FBATransportationFee' as NameEnum,
        FBAFulfillmentCODFee: 'FBAFulfillmentCODFee' as NameEnum
    };
}