/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { Quantity } from './quantity';
import { Timestamp } from './timestamp';

/**
 * Item information for a fulfillment order.
 */
export interface FulfillmentOrderItem { 
    /**
     * The seller SKU of the item.
     */
    sellerSKU: string;
    /**
     * The fulfillment order item identifier that you created and submitted with the createFulfillmentOrder operation.
     */
    sellerFulfillmentOrderItemId: string;
    quantity: Quantity;
    /**
     * A message to the gift recipient, if applicable.
     */
    giftMessage?: string;
    /**
     * Item-specific text that displays in recipient-facing materials such as the outbound shipment packing slip.
     */
    displayableComment?: string;
    /**
     * Amazon's fulfillment network SKU of the item.
     */
    fulfillmentNetworkSKU?: string;
    /**
     * **TBD** Indicates the disposition of the inventory.
     */
    orderItemDisposition?: string;
    cancelledQuantity: Quantity;
    unfulfillableQuantity: Quantity;
    estimatedShipDateTime?: Timestamp;
    estimatedArrivalDateTime?: Timestamp;
    perUnitPrice?: Currency;
    perUnitTax?: Currency;
    perUnitDeclaredValue?: Currency;
}