/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Timestamp } from './timestamp';

/**
 * Package information for a shipment in a fulfillment order.
 */
export interface FulfillmentShipmentPackage { 
    /**
     * Identifies a package in a shipment.
     */
    packageNumber: number;
    /**
     * Identifies the carrier who will deliver the shipment to the recipient.
     */
    carrierCode: string;
    /**
     * The tracking number, if provided, can be used to obtain tracking and delivery information.
     */
    trackingNumber?: string;
    estimatedArrivalDateTime?: Timestamp;
}