/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Indicates if the return item has been processed by an Amazon fulfillment center.  Possible values:  * New - The return item has not yet been processed by an Amazon fulfillment center.  * Processed - The return item has been processed by an Amazon fulfillment center.
 */
export type FulfillmentReturnItemStatus = 'New' | 'Processed';

export const FulfillmentReturnItemStatus = {
    New: 'New' as FulfillmentReturnItemStatus,
    Processed: 'Processed' as FulfillmentReturnItemStatus
};