/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FulfillmentOrderStatus = 'New' | 'Received' | 'Planning' | 'Processing' | 'Cancelled' | 'Complete' | 'CompletePartialled' | 'Unfulfillable' | 'Invalid';

export const FulfillmentOrderStatus = {
    New: 'New' as FulfillmentOrderStatus,
    Received: 'Received' as FulfillmentOrderStatus,
    Planning: 'Planning' as FulfillmentOrderStatus,
    Processing: 'Processing' as FulfillmentOrderStatus,
    Cancelled: 'Cancelled' as FulfillmentOrderStatus,
    Complete: 'Complete' as FulfillmentOrderStatus,
    CompletePartialled: 'CompletePartialled' as FulfillmentOrderStatus,
    Unfulfillable: 'Unfulfillable' as FulfillmentOrderStatus,
    Invalid: 'Invalid' as FulfillmentOrderStatus
};