/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Quantity } from './quantity';
import { Weight } from './weight';

/**
 * Item information for a shipment in a fulfillment order preview.
 */
export interface FulfillmentPreviewItem { 
    /**
     * The seller SKU of the item.
     */
    sellerSKU: string;
    quantity: Quantity;
    /**
     * A fulfillment order item identifier that you created with a call to the getFulfillmentPreview operation.
     */
    sellerFulfillmentOrderItemId: string;
    estimatedShippingWeight?: Weight;
    /**
     * The method used to calculate EstimatedShippingWeight.  Possible values:  * Package - Based on the actual weight of the items.  * Dimensional - Based on the cubic space that the items occupy.
     */
    shippingWeightCalculationMethod?: FulfillmentPreviewItem.ShippingWeightCalculationMethodEnum;
}
export namespace FulfillmentPreviewItem {
    export type ShippingWeightCalculationMethodEnum = 'Package' | 'Dimensional';
    export const ShippingWeightCalculationMethodEnum = {
        Package: 'Package' as ShippingWeightCalculationMethodEnum,
        Dimensional: 'Dimensional' as ShippingWeightCalculationMethodEnum
    };
}