/**
 * Listings
 * These APIs allow access to pricing data of offers listed by authorizing selling partners as well as certain competitive pricing data related to offers by other selling partners on Amazon.
 *
 * OpenAPI spec version: v1
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Workflow used to fulfill the order. Options include the Amazon Fulfillment Network or Marketplace Fulfillment Network.
 */
export type FulfillmentNetwork = 'AFN' | 'MFN';

export const FulfillmentNetwork = {
    AFN: 'AFN' as FulfillmentNetwork,
    MFN: 'MFN' as FulfillmentNetwork
};