/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeeList } from './feeList';
import { FulfillmentPreviewShipmentList } from './fulfillmentPreviewShipmentList';
import { ScheduledDeliveryInfo } from './scheduledDeliveryInfo';
import { ShippingSpeedCategory } from './shippingSpeedCategory';
import { StringList } from './stringList';
import { UnfulfillablePreviewItemList } from './unfulfillablePreviewItemList';
import { Weight } from './weight';

/**
 * Information about a fulfillment order preview, including delivery and fee information based on shipping method.
 */
export interface FulfillmentPreview { 
    shippingSpeedCategory: ShippingSpeedCategory;
    scheduledDeliveryInfo?: ScheduledDeliveryInfo;
    /**
     * Indicates whether this fulfillment order preview is fulfillable.
     */
    isFulfillable: boolean;
    /**
     * Indicates whether this fulfillment order preview is for COD (Cash On Delivery).
     */
    isCODCapable: boolean;
    estimatedShippingWeight?: Weight;
    estimatedFees?: FeeList;
    fulfillmentPreviewShipments?: FulfillmentPreviewShipmentList;
    unfulfillablePreviewItems?: UnfulfillablePreviewItemList;
    orderUnfulfillableReasons?: StringList;
    /**
     * The marketplace the fulfillment order is placed against.
     */
    marketplaceId: string;
}