/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Specifies whether the fulfillment order should ship now or have an order hold put on it.  Possible values:  * Ship - The fulfillment order ships now.  * Hold - An order hold is put on the fulfillment order.
 */
export type FulfillmentAction = 'Ship' | 'Hold';

export const FulfillmentAction = {
    Ship: 'Ship' as FulfillmentAction,
    Hold: 'Hold' as FulfillmentAction
};