/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Quantity } from './quantity';

/**
 * Item information for a shipment in a fulfillment order.
 */
export interface FulfillmentShipmentItem { 
    /**
     * The seller SKU of the item.
     */
    sellerSKU: string;
    /**
     * The fulfillment order item identifier that you created and submitted with the createFulfillmentOrder operation.
     */
    sellerFulfillmentOrderItemId: string;
    quantity: Quantity;
    /**
     * An identifier for the package that contains the item quantity.
     */
    packageNumber?: number;
}