/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The FulfillmentPolicy value that you chose when you submitted the CreateFulfillmentOrder operation.  Possible values:  * FillOrKill - If an item in a fulfillment order is determined to be unfulfillable before any shipment in the order has acquired the status of Pending (the process of picking units from inventory has begun), then the entire order is considered unfulfillable. However, if an item in a fulfillment order is determined to be unfulfillable after a shipment in the order has acquired the status of Pending, Amazon cancels as much of the fulfillment order as possible. See the FulfillmentShipment datatype for shipment status definitions.  * FillAll - All fulfillable items in the fulfillment order are shipped. The fulfillment order remains in a processing state until all items are either shipped by Amazon or cancelled by the seller.  * FillAllAvailable - All fulfillable items in the fulfillment order are shipped. All unfulfillable items in the order are cancelled by Amazon.
 */
export type FulfillmentPolicy = 'FillOrKill' | 'FillAll' | 'FillAllAvailable';

export const FulfillmentPolicy = {
    FillOrKill: 'FillOrKill' as FulfillmentPolicy,
    FillAll: 'FillAll' as FulfillmentPolicy,
    FillAllAvailable: 'FillAllAvailable' as FulfillmentPolicy
};