/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FulfillmentShipmentItemList } from './fulfillmentShipmentItemList';
import { FulfillmentShipmentPackageList } from './fulfillmentShipmentPackageList';
import { Timestamp } from './timestamp';

/**
 * Delivery and item information for a shipment in a fulfillment order.
 */
export interface FulfillmentShipment { 
    /**
     * A shipment identifier assigned by Amazon.
     */
    amazonShipmentId: string;
    /**
     * An identifier for the Amazon fulfillment center that the shipment will be sent from.
     */
    fulfillmentCenterId: string;
    /**
     * The current status of the shipment.  Possible values:  * PENDING - The process of picking units from inventory has begun.  * SHIPPED - All packages in the shipment have left the fulfillment center.  * CANCELLED_BY_FULFILLER - The Amazon fulfillment center could not fulfill the shipment as planned. This might be because the inventory was not at the expected location in the fulfillment center. After cancelling the fulfillment order, Amazon immediately creates a new fulfillment shipment and again attempts to fulfill the order.  * CANCELLED_BY_SELLER - The shipment was cancelled using the CancelFulfillmentOrder request.
     */
    fulfillmentShipmentStatus: FulfillmentShipment.FulfillmentShipmentStatusEnum;
    shippingDateTime?: Timestamp;
    estimatedArrivalDateTime?: Timestamp;
    fulfillmentShipmentItem: FulfillmentShipmentItemList;
    fulfillmentShipmentPackage?: FulfillmentShipmentPackageList;
}
export namespace FulfillmentShipment {
    export type FulfillmentShipmentStatusEnum = 'PENDING' | 'SHIPPED' | 'CANCELLED_BY_FULFILLER' | 'CANCELLED_BY_SELLER';
    export const FulfillmentShipmentStatusEnum = {
        PENDING: 'PENDING' as FulfillmentShipmentStatusEnum,
        SHIPPED: 'SHIPPED' as FulfillmentShipmentStatusEnum,
        CANCELLEDBYFULFILLER: 'CANCELLED_BY_FULFILLER' as FulfillmentShipmentStatusEnum,
        CANCELLEDBYSELLER: 'CANCELLED_BY_SELLER' as FulfillmentShipmentStatusEnum
    };
}