/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Quantity } from './quantity';

/**
 * Item information for a fulfillment order preview.
 */
export interface GetFulfillmentPreviewItem { 
    /**
     * The seller SKU of the item.
     */
    sellerSKU: string;
    quantity: Quantity;
    /**
     * A fulfillment order item identifier that you create to track items in your fulfillment preview.
     */
    sellerFulfillmentOrderItemId: string;
}