/**
 * Listings
 * These APIs allow access to pricing data of offers listed by authorizing selling partners as well as certain competitive pricing data related to offers by other selling partners on Amazon.
 *
 * OpenAPI spec version: v1
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Condition } from './condition';
import { DetailedShippingTime } from './detailedShippingTime';
import { FulfillmentNetwork } from './fulfillmentNetwork';
import { SellerFeedback } from './sellerFeedback';
import { ShipsFromType } from './shipsFromType';
import { SubCondition } from './subCondition';

/**
 * A list of Offer elements, including Points, ShippingTime, Shipping, ShipsFrom, ListingPrice, SellerFeedbackRating, and more. This list is the same length as the TotalOfferCount provided in the Summary or 20, whichever is less.
 */
export interface Offer { 
    fulfillmentChannel?: FulfillmentNetwork;
    itemCondition?: Condition;
    itemSubcondition?: SubCondition;
    sellerFeedbackRating?: SellerFeedback;
    shippingTime?: DetailedShippingTime;
    shipsFrom?: ShipsFromType;
    /**
     * true if the offer is currently in the Buy Box. There can be up to two Buy Box winners at any time per ASIN, one that is eligible for Prime and one that is not eligible for Prime.
     */
    isBuyBoxWinner?: boolean;
    /**
     * true if the seller of the item is eligible to win the Buy Box.
     */
    isFeaturedMerchant?: boolean;
    /**
     * true if this is your offer.
     */
    myOffer?: boolean;
}