/**
 * Listings
 * These APIs allow access to pricing data of offers listed by authorizing selling partners as well as certain competitive pricing data related to offers by other selling partners on Amazon.
 *
 * OpenAPI spec version: v1
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Condition } from './condition';
import { LowestPricedOffersSummary } from './lowestPricedOffersSummary';
import { Offer } from './offer';
import { Status } from './status';

/**
 * Offer details includes Points, ShippingTime, Shipping, ShipsFrom, ListingPrice, SellerFeedbackRating, and more.
 */
export interface Offers { 
    /**
     * The Amazon Standard Identification Number (ASIN) of a product (catalog item).
     */
    asin?: string;
    /**
     * The seller SKU of the item.
     */
    sku?: string;
    /**
     * Obfuscated identifier for a marketplace. | For example, ATVPDKIKX0DER indicates the US marketplace.
     */
    marketplaceId?: string;
    status?: Status;
    itemCondition?: Condition;
    /**
     * Date time in the the RFC 3339 format.
     */
    timeOfOfferChange?: string;
    summary?: LowestPricedOffersSummary;
    offers?: Array<Offer>;
}