/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A return reason code, a description, and an optional description translation.
 */
export interface ReasonCodeDetails { 
    /**
     * A code that indicates a valid return reason.
     */
    returnReasonCode: string;
    /**
     * A human readable description of the return reason code.
     */
    description: string;
    /**
     * A translation of the description. The translation is in the language specified in the Language request parameter.
     */
    translatedDescription?: string;
}