/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FulfillmentReturnItemStatus } from './fulfillmentReturnItemStatus';
import { ReturnItemDisposition } from './returnItemDisposition';
import { Timestamp } from './timestamp';

/**
 * An item that Amazon accepted for return.
 */
export interface ReturnItem { 
    /**
     * An identifier assigned by the seller to the return item.
     */
    sellerReturnItemId: string;
    /**
     * The identifier assigned to the item by the seller when the fulfillment order was created.
     */
    sellerFulfillmentOrderItemId: string;
    /**
     * The identifier for the shipment that is associated with the return item.
     */
    amazonShipmentId: string;
    /**
     * The return reason code assigned to the return item by the seller.
     */
    sellerReturnReasonCode: string;
    /**
     * An optional comment about the return item.
     */
    returnComment?: string;
    /**
     * The return reason code that the Amazon fulfillment center assigned to the return item.
     */
    amazonReturnReasonCode?: string;
    status: FulfillmentReturnItemStatus;
    statusChangedDate: Timestamp;
    /**
     * Identifies the return authorization used to return this item. See ReturnAuthorization.
     */
    returnAuthorizationId?: string;
    returnReceivedCondition?: ReturnItemDisposition;
    /**
     * The identifier for the Amazon fulfillment center that processed the return item.
     */
    fulfillmentCenterId?: string;
}