/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

/**
 * Return authorization information for items accepted for return.
 */
export interface ReturnAuthorization { 
    /**
     * An identifier for the return authorization. This identifier associates return items with the return authorization used to return them.
     */
    returnAuthorizationId: string;
    /**
     * An identifier for the Amazon fulfillment center that the return items should be sent to.
     */
    fulfillmentCenterId: string;
    returnToAddress: Address;
    /**
     * The return merchandise authorization (RMA) that Amazon needs to process the return.
     */
    amazonRmaId: string;
    /**
     * A URL for a web page that contains the return authorization barcode and the mailing label. This does not include pre-paid shipping.
     */
    rmaPageURL: string;
}