/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The condition of the return item when received by an Amazon fulfillment center.  Possible values:  * Sellable - Item is in sellable condition.  * Defective - Item is defective.  * CustomerDamaged - Item was damaged by the buyer or the seller.  * CarrierDamaged - Item was damaged by the carrier.  * FulfillerDamaged - Item was damaged by Amazon.
 */
export type ReturnItemDisposition = 'Sellable' | 'Defective' | 'CustomerDamaged' | 'CarrierDamaged' | 'FulfillerDamaged';

export const ReturnItemDisposition = {
    Sellable: 'Sellable' as ReturnItemDisposition,
    Defective: 'Defective' as ReturnItemDisposition,
    CustomerDamaged: 'CustomerDamaged' as ReturnItemDisposition,
    CarrierDamaged: 'CarrierDamaged' as ReturnItemDisposition,
    FulfillerDamaged: 'FulfillerDamaged' as ReturnItemDisposition
};