/**
 * Listings
 * These APIs allow access to pricing data of offers listed by authorizing selling partners as well as certain competitive pricing data related to offers by other selling partners on Amazon.
 *
 * OpenAPI spec version: v1
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Represents the overall result of the operation with one of the following values- Success, ActiveButTooSoonForProcessing - the item is active but no offers can be displayed until OffersAvailableTime, NoBuyableOffers - the item is not being offered for sale, NoOfferDueToMissingShippingCharge - the shipping charge is absent (for example, when the shipping charge varies by region).
 */
export type Status = 'Success' | 'ActiveButTooSoonForProcessing' | 'NoBuyableOffer' | 'NoOfferDueToMissingShippingCharge';

export const Status = {
    Success: 'Success' as Status,
    ActiveButTooSoonForProcessing: 'ActiveButTooSoonForProcessing' as Status,
    NoBuyableOffer: 'NoBuyableOffer' as Status,
    NoOfferDueToMissingShippingCharge: 'NoOfferDueToMissingShippingCharge' as Status
};