/**
 * Listings
 * These APIs allow access to pricing data of offers listed by authorizing selling partners as well as certain competitive pricing data related to offers by other selling partners on Amazon.
 *
 * OpenAPI spec version: v1
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The subcondition of the item.
 */
export type SubCondition = 'New' | 'Mint' | 'Very Good' | 'Good' | 'Acceptable' | 'Poor' | 'Club' | 'OEM' | 'Warranty' | 'Refurbished Warranty' | 'Refurbished' | 'Open Box' | 'Any' | 'Other';

export const SubCondition = {
    New: 'New' as SubCondition,
    Mint: 'Mint' as SubCondition,
    VeryGood: 'Very Good' as SubCondition,
    Good: 'Good' as SubCondition,
    Acceptable: 'Acceptable' as SubCondition,
    Poor: 'Poor' as SubCondition,
    Club: 'Club' as SubCondition,
    OEM: 'OEM' as SubCondition,
    Warranty: 'Warranty' as SubCondition,
    RefurbishedWarranty: 'Refurbished Warranty' as SubCondition,
    Refurbished: 'Refurbished' as SubCondition,
    OpenBox: 'Open Box' as SubCondition,
    Any: 'Any' as SubCondition,
    Other: 'Other' as SubCondition
};