/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you fulfill Multi-Channel Fulfillment orders using your inventory in Amazon's fulfillment network. You can get information on potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Quantity } from './quantity';
import { StringList } from './stringList';

/**
 * Information about unfulfillable items in a fulfillment order preview.
 */
export interface UnfulfillablePreviewItem { 
    /**
     * The seller SKU of the item.
     */
    sellerSKU: string;
    quantity: Quantity;
    /**
     * A fulfillment order item identifier created with a call to the getFulfillmentPreview operation.
     */
    sellerFulfillmentOrderItemId: string;
    itemUnfulfillableReasons?: StringList;
}